# Site Settings
title: Clever Ladder
description: 'A handcrafted website that fits your demand.'
email: hello@cleverladder.com.com

#MENU ITEM LIST

menu:
- {name: Services, url: '#services'}
- {name: Our Work, url: '#work'}
- {name: The Process, url: '#the-process'}
- {name: Contact, url: '#contact'}


# Work Section
projects:
- {name: "#", folder: '#', file: '#'}

# Social Links
# social:
# - {icon: 'twitter', link: '#'}
# - {icon: 'linkedin', link: '#'}



# Change the site defaults here
logo: logo.svg
bg-img: hero-bg.jpg
